### ISSUE TITLE
[Idea] Automation of data collection

### ISSUE THREAD

**Issue by JanCaha** [MichaelChirico/r-ci-samples#3]
Looking at the repository and its purpose, it would be possible to set up GitHub Action based on Cron to automatically run the `update.sh` and commit the collected data directly into the repository.

Setting the Cron action to run every 48 hours or so would keep the repository reasonably up-to-date.

Is it something, that seems useful?

**Comment by MichaelChirico** [comment]
Sure, that sounds awesome, rather than relying on my machine to be awake to run the Cron.

I think you're quite familiar with GH Actions already, would you mind filing a PR for this?

**Comment by JanCaha** [comment]
It is part of the new [PR](https://github.com/MichaelChirico/r-ci-samples/pull/4).
